name: Lint OpenRPC

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Run `npx @open-rpc/openrpc-linter init if you don't have custom rules.
      - run: npx @open-rpc/openrpc-linter@0.0.18 lint openrpc.json -r rules.yml
